
pipeline {
    agent any

    stages {

        // stage('SonarQube analysis') {
        //   steps {
        //     script {
        //         scannerHome = tool 'sonar-scanner'
        //     }
        //     withSonarQubeEnv('sonarqube-server') {
        //       sh "${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=develop"
        //     }
        //   }
        // }

        stage('Build') {
            agent any
            steps {
                sh '/usr/local/bin/docker build -f Dockerfile -t website:latest .'

            }
        }

        stage('Test') {
            steps {
                sh 'docker run -it --rm website:latest npm test'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d -it --rm -p 3000:3000 --name my_website website:latest'
            }
        }
    }
}
