
pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub_id')
    }
    stages {

        stage('Build') {
            agent any
            steps {
                sh '/usr/local/bin/docker build -f Dockerfile -t website:latest .'

            }
        }

        // stage('Test') {
        //     steps {
        //         sh '/usr/local/bin/docker run --rm website:latest npm test'
        //     }
        // }
        
        // stage('SonarQube analysis') {
        //   steps {
        //     sh 'export PATH=/opt/homebrew/Cellar/openjdk/21.0.3/bin:$PATH && java -version'
        //     script {
        //         scannerHome = tool 'sonar-scanner'
        //     }
        //     withSonarQubeEnv('sonar-server') {
        //       sh "export PATH=/opt/homebrew/Cellar/openjdk/21.0.3/bin:$PATH && ${scannerHome}/bin/sonar-scanner -Dsonar.projectKey=develop"
        //     }
        //   }
        // }

        // stage('Push to Docker Hub') {
        //     steps {
        //         script {
        //             docker.withRegistry('https://index.docker.io/v1/', 'DOCKER_HUB_CREDENTIALS') {
        //                 sh '/usr/local/bin/docker tag website:latest quxch/website:latest'
        //                 sh '/usr/local/bin/docker push quxch/website:latest'
        //             }
        //         }
        //     }
        // }

        // stage('Deploy') {
        //     steps {
        //         sh '/usr/local/bin/docker run -d --rm -p 3000:3000 --name my_website website:latest'
        //     }
        // }
        stage('Deploy') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'dockerhub_id', url: 'https://index.docker.io/v1/') {
                        docker.image('website:latest').push()
                    }
                }

            }
        }

    }
}
