
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // sh 'npm install'
                sh 'npm install --save express'
                sh 'npm install --save-dev jest'
                sh 'npm install --save-dev supertest'
                sh 'npm run build'
                archiveArtifacts artifacts: '**/*.jar', allowEmptyArchive: true
          
            }
        }
        stage('Test') {
            steps {
                // sh './jenkins/scripts/test.sh'
                sh 'npm test'

            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
                input message: 'Finished using the web site? (Click "Proceed" to continue)' 
                sh './jenkins/scripts/kill.sh' 
            }
        }
    }
}